[pytest]
addopts =
    -n 4
    -s -v
    --alluredir=allure-results
    --reruns 3
    --reruns-delay 1

markers =
    basket: tests connected with basket
    guest: tests for unauthorized user
    login: tests connected with Login Page
    main_page
    need_review: tests for peer-to-peer review
    product_page
    regression
    smoke
    user: tests for authorized user