[pytest]
addopts =
    -n 4
    -s -v
    --alluredir=allure-results
    --reruns 3
    --reruns-delay 1

markers =
    guest: tests for unauthenticated user
    login: tests connected with authentication
    main_page
    regression
    smoke